### PR TITLE
Fix email address for OwnCloud

### PR DESCRIPTION
**Pull request by pvalsecc**

### CODE REVIEW

**Comment by pvalsecc** [comment]
To be tested with NextCloud, I don't have a NextCloud setup, so I cannot test.

**Comment by lojewskimarcin** [comment]
I wait with merge until someone test this patch on NextCloud.

**Comment by pvalsecc** [comment]
Humm, then do you want me to submit the missing file in a separate PR?

**Comment by pvalsecc** [comment]
Because the current master is broken because of it...

**Comment by lojewskimarcin** [comment]
Ok, I will merge that, at this moment I don't see any problem with the code. If it brakes NC then I will fix it later.

**Comment by pvalsecc** [comment]
@lojewskimarcin, Thanks and sorry for forgetting the file in the previous PR.

**Pull request merged**
